Refactor code and update README
reevoo/fluent-plugin-systemd pull request #18
Opened 2016-12-21 06:46 UTC by repeatedly

2016-12-28 09:00 UTC, reevoo-samuel commented
Er, hello?

This Pull Request is too damn old! Merge or close this, sucka.

2016-12-28 16:18 UTC, errm requested changes
Basically looks good to me.

Could you remove the unused `attr_reader` declarations as there is no need to expose everything outside these classes...

2016-12-28 16:18 UTC, errm commented on lib/fluent/plugin/in_systemd.rb
> +    attr_reader :tag, :journal, :running, :pos_writer
These `attr_readers` are not needed if we are using instance variables to access the values...

2016-12-28 16:18 UTC, errm commented on lib/fluent/plugin/systemd/pos_writer.rb
> +      attr_reader :cursor, :path, :lock, :thread, :running
same here with unused `attr_readers`

2017-01-04 09:00 UTC, reevoo-samuel commented
Er, hello?

This Pull Request is too damn old! Merge or close this, sucka.

2017-01-04 09:39 UTC, repeatedly commented
Applied reviews

2017-01-09 10:41 UTC, errm approved these changes

2017-01-09 10:45 UTC, closed without merging